# Generated by Django 5.2.10 on 2026-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_fix_meta_test_mode_scope_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('BOT', 'Bot')], default='BOT', max_length=30)),
                ('token_encrypted', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empresas_telegram_bot',
                'ordering': ['-actualizado_en', '-id'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='telegram_chat_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
