# Generated by Django 5.2.10 on 2026-03-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0016_telegrambot_empresa_telegram_chat_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="kommo_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empresa",
            name="kommo_access_token",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="empresa",
            name="kommo_account_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="kommo_subdomain",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
