# Generated by Django 5.2.10 on 2026-03-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0017_empresa_kommo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="kommo_webhook_secret",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
