# Generated by Django 5.2.10 on 2026-04-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0018_empresa_kommo_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_prefijo',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
