# Generated by Django 5.2.10 on 2026-01-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bms', to='empresas.empresa')),
            ],
            options={
                'db_table': 'pauta_bm',
            },
        ),
        migrations.CreateModel(
            name='Campaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('objetivo', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campañas', to='empresas.empresa')),
            ],
            options={
                'db_table': 'pauta_campaña',
            },
        ),
        migrations.CreateModel(
            name='ConjuntoAnuncios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=50)),
                ('presupuesto_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('segmentacion', models.JSONField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('campaña', models.ForeignKey(db_column='campaña_id', on_delete=django.db.models.deletion.CASCADE, related_name='conjuntos_anuncios', to='pauta.campaña')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjuntos_anuncios', to='empresas.empresa')),
            ],
            options={
                'db_table': 'pauta_conjuntoanuncios',
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=50)),
                ('contenido', models.JSONField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='empresas.empresa')),
                ('conjunto_anuncios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='pauta.conjuntoanuncios')),
            ],
            options={
                'db_table': 'pauta_anuncio',
            },
        ),
        migrations.CreateModel(
            name='CredencialesMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_id', models.CharField(max_length=100)),
                ('app_id', models.CharField(max_length=100)),
                ('token_acceso_encrypted', models.TextField()),
                ('bm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales_meta', to='pauta.bm')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales_meta', to='empresas.empresa')),
            ],
            options={
                'db_table': 'pauta_credencialesmeta',
            },
        ),
        migrations.CreateModel(
            name='CuentaPublicitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_publicitarias', to='pauta.bm')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_publicitarias', to='empresas.empresa')),
            ],
            options={
                'db_table': 'pauta_cuentapublicitaria',
            },
        ),
        migrations.AddField(
            model_name='campaña',
            name='cuenta_publicitaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campañas', to='pauta.cuentapublicitaria'),
        ),
        migrations.CreateModel(
            name='GastoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('monto_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta_publicitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_diarios', to='pauta.cuentapublicitaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_diarios', to='empresas.empresa')),
            ],
            options={
                'db_table': 'pauta_gastodiario',
            },
        ),
    ]
