# Generated by Django 5.2.10 on 2026-02-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('pauta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='contenido',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='meta_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conjuntoanuncios',
            name='segmentacion',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('primary_text', models.TextField()),
                ('headline', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('url_destino', models.URLField()),
                ('cta', models.CharField(max_length=50)),
                ('meta_id', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'db_table': 'pauta_creative',
            },
        ),
        migrations.AddField(
            model_name='anuncio',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anuncios', to='pauta.creative'),
        ),
        migrations.CreateModel(
            name='FanPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanpages', to='pauta.bm')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanpages', to='empresas.empresa')),
            ],
            options={
                'db_table': 'pauta_fanpage',
            },
        ),
        migrations.AddField(
            model_name='creative',
            name='fanpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creatives', to='pauta.fanpage'),
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('fanpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_account', to='pauta.fanpage')),
            ],
            options={
                'db_table': 'pauta_instagram_account',
            },
        ),
        migrations.AddField(
            model_name='creative',
            name='instagram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creatives', to='pauta.instagramaccount'),
        ),
        migrations.CreateModel(
            name='PautaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('s3_url', models.URLField()),
                ('meta_asset_id', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='pending', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'db_table': 'pauta_asset',
            },
        ),
        migrations.AddField(
            model_name='creative',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pauta.pautaasset'),
        ),
    ]
