# Generated by Django 5.2.10 on 2026-02-06 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0002_remove_anuncio_contenido_alter_anuncio_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='creative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anuncios', to='pauta.creative'),
        ),
    ]
