# Generated by Django 5.2.10 on 2026-02-16 23:19

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_bm_organizacion(apps, schema_editor):
    BM = apps.get_model("pauta", "BM")
    Empresa = apps.get_model("empresas", "Empresa")
    empresa_org = {
        empresa.id: empresa.organizacion_id
        for empresa in Empresa.objects.all().only("id", "organizacion_id")
    }
    for bm in BM.objects.all().only("id", "empresa_id"):
        org_id = empresa_org.get(bm.empresa_id)
        if org_id:
            BM.objects.filter(id=bm.id).update(organizacion_id=org_id)


def backwards_copy_bm_empresa(apps, schema_editor):
    BM = apps.get_model("pauta", "BM")
    Empresa = apps.get_model("empresas", "Empresa")
    org_empresa = {}
    for empresa in Empresa.objects.all().only("id", "organizacion_id").order_by("id"):
        if empresa.organizacion_id and empresa.organizacion_id not in org_empresa:
            org_empresa[empresa.organizacion_id] = empresa.id
    for bm in BM.objects.all().only("id", "organizacion_id"):
        empresa_id = org_empresa.get(bm.organizacion_id)
        if empresa_id:
            BM.objects.filter(id=bm.id).update(empresa_id=empresa_id)


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_usuario_organizacion'),
        ('pauta', '0009_actualizar_sync_pauta_cada_4hs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bm',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bms', to='empresas.organizacion'),
        ),
        migrations.RunPython(forwards_copy_bm_organizacion, backwards_copy_bm_empresa),
        migrations.RemoveField(
            model_name='bm',
            name='empresa',
        ),
    ]
