# Generated by Django 5.2.10 on 2026-02-22 17:03

from django.db import migrations, models


def backfill_bm_empresas(apps, schema_editor):
    BM = apps.get_model("pauta", "BM")
    CuentaPublicitaria = apps.get_model("pauta", "CuentaPublicitaria")
    FanPage = apps.get_model("pauta", "FanPage")
    CredencialesMeta = apps.get_model("pauta", "CredencialesMeta")

    for bm in BM.objects.all():
        empresa_ids = set(
            CuentaPublicitaria.objects.filter(bm_id=bm.id).values_list("empresa_id", flat=True)
        )
        empresa_ids.update(
            FanPage.objects.filter(bm_id=bm.id).values_list("empresa_id", flat=True)
        )
        empresa_ids.update(
            CredencialesMeta.objects.filter(bm_id=bm.id).values_list("empresa_id", flat=True)
        )
        if empresa_ids:
            bm.empresas.add(*empresa_ids)


def reverse_backfill_bm_empresas(apps, schema_editor):
    BM = apps.get_model("pauta", "BM")
    for bm in BM.objects.all():
        bm.empresas.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_fix_meta_test_mode_scope_db'),
        ('pauta', '0010_remove_bm_empresa_bm_organizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bm',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='bms', to='empresas.empresa'),
        ),
        migrations.RunPython(backfill_bm_empresas, reverse_backfill_bm_empresas),
    ]
