# Generated by Django 5.2.10 on 2026-02-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0011_bm_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencialesmeta',
            name='nombre',
            field=models.CharField(default='Credencial Meta', max_length=120),
        ),
        migrations.AlterField(
            model_name='credencialesmeta',
            name='app_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
