# Generated by Django 5.2.10 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pauta", "0012_credencialesmeta_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuentapublicitaria",
            name="moneda",
            field=models.CharField(
                choices=[("USD", "USD"), ("ARS", "ARS")],
                default="USD",
                max_length=3,
            ),
        ),
    ]

