# Generated by Django 5.2.10 on 2026-02-24 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0013_cuentapublicitaria_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='estado',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='pautaasset',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='creative',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pauta.pautaasset'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='cta',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='creative',
            name='fanpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creatives', to='pauta.fanpage'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='creative',
            name='primary_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='creative',
            name='url_destino',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pautaasset',
            name='s3_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
