# Generated by Codex on 2026-03-27

from django.db import migrations, models


def backfill_credencialesmeta_empresas(apps, schema_editor):
    CredencialesMeta = apps.get_model("pauta", "CredencialesMeta")

    through = CredencialesMeta.empresas.through
    rows = []
    seen = set()
    for cred in CredencialesMeta.objects.exclude(empresa_id__isnull=True).only("id", "empresa_id"):
        key = (cred.id, cred.empresa_id)
        if key in seen:
            continue
        seen.add(key)
        rows.append(
            through(
                credencialesmeta_id=cred.id,
                empresa_id=cred.empresa_id,
            )
        )
    if rows:
        through.objects.bulk_create(rows, ignore_conflicts=True)


def reverse_backfill_credencialesmeta_empresas(apps, schema_editor):
    CredencialesMeta = apps.get_model("pauta", "CredencialesMeta")
    through = CredencialesMeta.empresas.through
    through.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pauta", "0014_creative_estado_pautaasset_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credencialesmeta",
            name="empresas",
            field=models.ManyToManyField(
                blank=True,
                related_name="credenciales_meta_compartidas",
                to="empresas.empresa",
            ),
        ),
        migrations.RunPython(
            backfill_credencialesmeta_empresas,
            reverse_backfill_credencialesmeta_empresas,
        ),
    ]
