web: python manage.py migrate --noinput && gunicorn configs.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
worker: celery -A configs worker -l info
beat: celery -A configs beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
