web: gunicorn configs.asgi:application -k gunicorn.workers.gasgi.ASGIWorker --bind 0.0.0.0:$PORT
worker: celery -A configs worker -l info
beat: celery -A configs beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
