# Generated by Django 5.2.10 on 2026-01-26 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('recursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cant_compras', models.IntegerField(default=0)),
                ('total_compras_ars', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_compras_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresas.empresa')),
            ],
            options={
                'db_table': 'operativo_cliente',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('monto_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tc', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='operativo.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='empresas.empresa')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to=settings.AUTH_USER_MODEL)),
                ('tipo_cambio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='recursos.tipocambio')),
            ],
            options={
                'db_table': 'operativo_compra',
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('url', models.URLField()),
                ('bono', models.CharField(choices=[('100%', '100%'), ('50%', '50%'), ('25%', '25%'), ('30%', '30%')], default='100%', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landings', to='empresas.empresa')),
            ],
            options={
                'db_table': 'operativo_landing',
            },
        ),
        migrations.CreateModel(
            name='EventosMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('lead', 'Lead'), ('contact', 'Contact'), ('purchase', 'Purchase')], max_length=50)),
                ('data', models.JSONField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('reintentos', models.IntegerField(default=0)),
                ('respuesta_meta', models.JSONField(blank=True, null=True)),
                ('fbc', models.CharField(blank=True, max_length=255, null=True)),
                ('fbp', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_meta', to='operativo.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_meta', to='empresas.empresa')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_meta', to=settings.AUTH_USER_MODEL)),
                ('landing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_meta', to='operativo.landing')),
            ],
            options={
                'db_table': 'operativo_eventosmeta',
            },
        ),
    ]
