# Generated by Django 5.2.10 on 2026-02-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0003_remove_landing_content_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landing',
            name='boton_texto',
        ),
        migrations.RemoveField(
            model_name='landing',
            name='boton_url',
        ),
    ]
