# Generated by Django 5.2.10 on 2026-02-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0004_remove_landing_boton_texto_remove_landing_boton_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='background_url_horizontal',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='background_url_vertical',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='texto_boton',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='texto_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
