# Generated by Django 5.2.10 on 2026-02-06 22:32

import apps.operativo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0005_landing_background_url_horizontal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landing',
            name='background_url_horizontal',
        ),
        migrations.RemoveField(
            model_name='landing',
            name='background_url_vertical',
        ),
        migrations.AddField(
            model_name='landing',
            name='background_horizontal',
            field=models.ImageField(blank=True, null=True, upload_to=apps.operativo.models.Landing._landing_upload_to),
        ),
        migrations.AddField(
            model_name='landing',
            name='background_vertical',
            field=models.ImageField(blank=True, null=True, upload_to=apps.operativo.models.Landing._landing_upload_to),
        ),
    ]
