# Generated by Django 5.2.10 on 2026-02-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0006_remove_landing_background_url_horizontal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='idempotency_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
