# Generated by Django 5.2.10 on 2026-02-07 04:57

import apps.operativo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0007_cliente_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comprobante_archivo',
            field=models.FileField(blank=True, null=True, upload_to=apps.operativo.models.Compra._comprobante_upload_to),
        ),
    ]
