# Generated by Django 5.2.10 on 2026-02-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0018_cliente_attribution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='texto_whatsapp',
            field=models.TextField(blank=True, default=''),
        ),
    ]
