# Generated by Django 5.2.10 on 2026-02-18 18:01

import apps.operativo.models
import apps.operativo.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0020_landing_mostrar_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comprobante_archivo',
            field=models.FileField(blank=True, null=True, storage=apps.operativo.storages.PrivateMediaStorage(), upload_to=apps.operativo.models.Compra._comprobante_upload_to),
        ),
        migrations.AlterField(
            model_name='landing',
            name='background_horizontal',
            field=models.ImageField(blank=True, null=True, storage=apps.operativo.storages.PublicMediaStorage(), upload_to=apps.operativo.models.Landing._landing_upload_to),
        ),
        migrations.AlterField(
            model_name='landing',
            name='background_vertical',
            field=models.ImageField(blank=True, null=True, storage=apps.operativo.storages.PublicMediaStorage(), upload_to=apps.operativo.models.Landing._landing_upload_to),
        ),
    ]
