# Generated by Django 5.2.10 on 2026-02-21 02:49

import apps.operativo.models
import apps.operativo.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_usuario_organizacion'),
        ('operativo', '0021_alter_compra_comprobante_archivo_and_more'),
        ('recursos', '0004_heartbeat_cada_10_min'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='bono_ars',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compra',
            name='bono_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.CharField(blank=True, max_length=255, null=True)),
                ('comprobante_archivo', models.FileField(blank=True, null=True, storage=apps.operativo.storages.PrivateMediaStorage(), upload_to=apps.operativo.models.Retiro._comprobante_upload_to)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('monto_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tc', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='operativo.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='empresas.empresa')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros', to=settings.AUTH_USER_MODEL)),
                ('tipo_cambio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros', to='recursos.tipocambio')),
            ],
            options={
                'db_table': 'operativo_retiro',
            },
        ),
    ]
