# Generated by Django 5.2.10 on 2026-02-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0022_compra_bono_ars_compra_bono_usd_retiro'),
        ('pauta', '0012_credencialesmeta_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='credencial_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landings', to='pauta.credencialesmeta'),
        ),
    ]
