# Generated by Django 5.2.10 on 2026-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operativo", "0023_landing_credencial_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="landing",
            name="font_family",
            field=models.CharField(default="roboto", max_length=40),
        ),
        migrations.AddField(
            model_name="landing",
            name="font_scale",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="landing",
            name="form_bg_color",
            field=models.CharField(default="#000000", max_length=20),
        ),
        migrations.AddField(
            model_name="landing",
            name="form_field_border_color",
            field=models.CharField(default="#e014ff", max_length=20),
        ),
    ]
