# Generated by Django 5.2.10 on 2026-03-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operativo", "0024_landing_form_style_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="landing",
            name="font_bono",
            field=models.CharField(default="roboto", max_length=40),
        ),
        migrations.AddField(
            model_name="landing",
            name="font_boton",
            field=models.CharField(default="roboto", max_length=40),
        ),
        migrations.AddField(
            model_name="landing",
            name="font_form",
            field=models.CharField(default="roboto", max_length=40),
        ),
        migrations.AddField(
            model_name="landing",
            name="font_info",
            field=models.CharField(default="roboto", max_length=40),
        ),
        migrations.AddField(
            model_name="landing",
            name="font_keyword",
            field=models.CharField(default="roboto", max_length=40),
        ),
        migrations.AddField(
            model_name="landing",
            name="font_subtitulo",
            field=models.CharField(default="roboto", max_length=40),
        ),
        migrations.AddField(
            model_name="landing",
            name="font_titulo",
            field=models.CharField(default="roboto", max_length=40),
        ),
        migrations.AddField(
            model_name="landing",
            name="form_bg_opacity",
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
        ),
        migrations.AddField(
            model_name="landing",
            name="size_bono",
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="landing",
            name="size_boton",
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=4),
        ),
        migrations.AddField(
            model_name="landing",
            name="size_form",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="landing",
            name="size_info",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="landing",
            name="size_keyword",
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="landing",
            name="size_subtitulo",
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
        ),
        migrations.AddField(
            model_name="landing",
            name="size_titulo",
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
        ),
    ]
