# Generated by Django 5.2.10 on 2026-03-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operativo", "0025_landing_typography_by_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="landing",
            name="weight_bono",
            field=models.PositiveSmallIntegerField(default=800),
        ),
        migrations.AddField(
            model_name="landing",
            name="weight_boton",
            field=models.PositiveSmallIntegerField(default=700),
        ),
        migrations.AddField(
            model_name="landing",
            name="weight_form",
            field=models.PositiveSmallIntegerField(default=400),
        ),
        migrations.AddField(
            model_name="landing",
            name="weight_info",
            field=models.PositiveSmallIntegerField(default=700),
        ),
        migrations.AddField(
            model_name="landing",
            name="weight_keyword",
            field=models.PositiveSmallIntegerField(default=700),
        ),
        migrations.AddField(
            model_name="landing",
            name="weight_subtitulo",
            field=models.PositiveSmallIntegerField(default=700),
        ),
        migrations.AddField(
            model_name="landing",
            name="weight_titulo",
            field=models.PositiveSmallIntegerField(default=800),
        ),
    ]
