# Generated by Django 5.2.10 on 2026-03-05 15:06

import apps.operativo.models
import apps.operativo.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0026_landing_text_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, default=apps.operativo.models.generar_codigo_corto, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='imagen_reemplazo_form',
            field=models.ImageField(blank=True, null=True, storage=apps.operativo.storages.PublicMediaStorage(), upload_to=apps.operativo.models.Landing._landing_upload_to),
        ),
        migrations.AddField(
            model_name='landing',
            name='mostrar_formulario',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
