# Generated by Django 5.2.10 on 2026-03-05 15:08

import random
import string
from collections import Counter
from django.db import migrations, models


def _gen_codigo():
    return "".join(random.choices(string.ascii_uppercase + string.digits, k=6))


def backfill_cliente_codigo(apps, schema_editor):
    Cliente = apps.get_model("operativo", "Cliente")
    used = set()
    existing = list(
        Cliente.objects.exclude(codigo__isnull=True)
        .exclude(codigo="")
        .values_list("codigo", flat=True)
    )
    normalized_counts = Counter((codigo or "").strip().upper() for codigo in existing)

    for cliente in Cliente.objects.order_by("id"):
        current = (cliente.codigo or "").strip().upper()
        if current and normalized_counts[current] == 1 and current not in used:
            used.add(current)
            if current != cliente.codigo:
                cliente.codigo = current
                cliente.save(update_fields=["codigo"])
            continue
        while True:
            candidate = _gen_codigo()
            if candidate not in used:
                used.add(candidate)
                cliente.codigo = candidate
                cliente.save(update_fields=["codigo"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0027_cliente_codigo_landing_imagen_reemplazo_form_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_cliente_codigo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
