# Generated by Django 5.2.10 on 2026-03-07 19:50

import apps.operativo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0028_alter_cliente_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='mostrar_comunidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landing',
            name='mostrar_medios_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landing',
            name='mostrar_pasos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landing',
            name='texto_comunidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='texto_pasos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default=apps.operativo.models.generar_codigo_corto, max_length=6, unique=True),
        ),
    ]
