# Generated by Django 5.2.10 on 2026-03-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0029_landing_mostrar_comunidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='color_bono',
            field=models.CharField(default='#ffe600', max_length=255),
        ),
        migrations.AlterField(
            model_name='landing',
            name='color_info',
            field=models.CharField(default='#ffffff', max_length=255),
        ),
        migrations.AlterField(
            model_name='landing',
            name='color_keyword',
            field=models.CharField(default='#ffe600', max_length=255),
        ),
        migrations.AlterField(
            model_name='landing',
            name='color_subtitulo',
            field=models.CharField(default='#ffffff', max_length=255),
        ),
        migrations.AlterField(
            model_name='landing',
            name='color_titulo',
            field=models.CharField(default='#ffffff', max_length=255),
        ),
        migrations.AlterField(
            model_name='landing',
            name='form_bg_color',
            field=models.CharField(default='#000000', max_length=255),
        ),
    ]
