# Generated by Codex on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operativo", "0033_landing_form_field_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventosmeta",
            name="ocurrido_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
