# Generated by Django 5.2.10 on 2026-04-07 00:19

import apps.operativo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0034_eventosmeta_ocurrido_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default=apps.operativo.models.generar_codigo_corto, max_length=8, unique=True),
        ),
    ]
