# Generated by Django 5.2.10 on 2026-04-07 02:38

import apps.operativo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0035_alter_cliente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default=apps.operativo.models.generar_codigo_corto, max_length=10, unique=True),
        ),
    ]
