# Generated by Django 5.2.10 on 2026-04-13 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0036_alter_cliente_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='ocurrido_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
