# Generated by Django 5.2.10 on 2026-01-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_origen', models.CharField(max_length=10)),
                ('moneda_destino', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fuente', models.CharField(blank=True, max_length=255, null=True)),
                ('vigente_desde', models.DateTimeField(auto_now=True)),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recursos_tipocambio',
            },
        ),
        migrations.CreateModel(
            name='WhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapps', to='empresas.empresa')),
            ],
            options={
                'db_table': 'recursos_whatsapp',
            },
        ),
    ]
